Exercise/Exercise_New/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  # resources :albums do
  #   resources :pictures
  # end

  # resources :users


  # shallow do
  resources :users, shallow: true do
    get 'dashboard', on: :member
    resources :albums do
      resources :pictures
    end
  end

  resources :pictures

  # end

  root 'home#index'
end

Exercise/Exercise_New/app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user
  has_many :pictures, dependent: :destroy
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/


   # Yêu cầu phải chọn ảnh
 # validates :image, attachment_presence: true
 # Kiểm tra kích thước ảnh
 # validates_attachment :image, size: { in: 0..100.kilobytes }
 # Kiểm tra loại ảnh
 # validates_attachment :image, content_type: { content_type: "image/jpg" }

 # Ta cũng có thể gộp 3 điều kiện trên:
 # validates_attachment :image, presence: true,
  # content_type: { content_type: "image/jpg" },
  # size: { in: 0..100.kilobytes }
end

Exercise/Exercise_New/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Exercise/Exercise_New/app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :album
  # belongs_to :user, through: :album

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

Exercise/Exercise_New/app/models/user.rb
class User < ApplicationRecord

  after_create :send_mail

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  # validates :name, presence: true
  has_many :albums
  has_many :pictures, through: :albums

  def send_mail
    Delayed::Job.enqueue(NotifyCreateStoreJob.new(id))
  end
end

Exercise/Exercise_New/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @user = User.find params[:user_id]
    @albums = @user.albums.page(params[:page]).per(2)
  end

  def new
    @album = Album.new
  end

  def show
    @album = Album.find(params[:id])
  end

  def edit
    @album = Album.find(params[:id])
  end

  def create

    @user = User.find params[:user_id]
    @album = @user.albums.create(album_params)
    redirect_to user_albums_path(@user)
  end

  def destroy

    @album = Album.find(params[:id])
    @user = @album.user
    @album.destroy
    redirect_to user_albums_path(@user)
  end

  def update
    # @user = User.find params[:user_id]
    @album = Album.find(params[:id])
    @user = @album.user
    @album.update(album_params)
    redirect_to user_albums_path(@user)
  end

  private
    def album_params
      params.require(:album).permit(:title,:desc,:is_public,:image)
    end

end

Exercise/Exercise_New/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

Exercise/Exercise_New/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

Exercise/Exercise_New/app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index

    # @user = User.find params[:user_id]
    # @album = @user.
    if params[:album_id] &&  @album = Album.find(params[:album_id])
      @pictures = @album.pictures.page(params[:page]).per(1)
    else
      @pictures = Picture.page(params[:page]).per(1)
    end
  end

  def new
    @album = Album.find(params[:album_id])
    @picture = @album.pictures.new
  end

  def edit
    # @album = Album.find(params[:album_id])
    @picture = Picture.find(params[:id])
  end

  def create
    @album = Album.find(params[:album_id])
    @picture = @album.pictures.create(picture_params)
    redirect_to album_pictures_path(@album)
  end

  def destroy
    # @album = Album.find(params[:album_id])
    @picture = Picture.find(params[:id])
    @album = @picture.album
    @picture.destroy
    redirect_to album_pictures_path(@album)
  end

  def update
    # @album = Album.find(params[:album_id])
    @picture = Picture.find(params[:id])
    @album = @picture.album
    @picture.update(picture_params)
    redirect_to album_pictures_path(@album)
  end

  private
  def picture_params
    params.require(:picture).permit(:title, :desc, :is_public, :image)
  end
end

Exercise/Exercise_New/app/controllers/users_controller.rb
class UsersController < ApplicationController
   # POST /users
  # POST /users.json
  # paginates_per 2

  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        UserMailer.welcome_email.deliver_lateR

        format.html { redirect_to(@user, notice: 'User was successfully created.') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def dashboard
    @pictures = current_user.pictures
  end

  def index
    # @users = User.all#find params[:id]
    @users = User.page(params[:page]).per(2)
  end

  def show
    @user = User.find params[:id]
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    @user.update(user_params)
    redirect_to users_path
    UserMailer.welcome_email.deliver_now
  end

  private
    def user_params
      params.require(:user).permit(:name)
    end
end

Exercise/Exercise_New/app/helpers/albums_helper.rb
module AlbumsHelper
end

Exercise/Exercise_New/app/helpers/application_helper.rb
module ApplicationHelper
end

Exercise/Exercise_New/app/helpers/home_helper.rb
module HomeHelper
end

Exercise/Exercise_New/app/helpers/pictures_helper.rb
module PicturesHelper
end

Exercise/Exercise_New/app/helpers/users_helper.rb
module UsersHelper
end

Exercise/Exercise_New/app/views/albums/_form.html.erb
<div>
  <div class="row">
    <div>
      <%= form_for album, url: url_link do |form| %>
      <div>
        <%= form.file_field :image %>
      </div>
      <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
      </p>

      <p>
        <%= form.label :description %><br>
        <%= form.text_area :desc %>
      </p>
      <p>
        <%= form.label :public %><br>
        <%= form.check_box :is_public %><br>
      </p>
      <p>
        <%= form.submit %>
      </p>

      <% end %>
    </div>
  </div>
</div>

Exercise/Exercise_New/app/views/albums/edit.html.erb
<h1><%= t('.title_edit_album') %></h1>
<%= render 'form', album: @album, url_link: album_path %>

Exercise/Exercise_New/app/views/albums/index.html.erb
<div>
  <div class="row bgForm">
    <% @albums.each do |album| %>
    <div class="col-md-3 col-xs-3 bgDivTest">

      <%= image_tag album.image.url %>
     <!--  <%= image_tag album.image.url(:medium) %>
      <%= image_tag album.image.url(:thumb) %> -->
      <div class="row">
        <div class="sizeText">
          <%= album.title %>
        </div>
      </div>
      <div class="row">
        <div class="sizeText">
          <%= album.desc %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-2 col-xs-2 col-md-offset-3 col-xs-offset-3 setMargin">
          <%= link_to t('.edit'), edit_album_path(album) %>
        </div>
        <div class="col-md-2 col-xs-2 setMargin">
          <%= link_to t('.show'), album_pictures_path(album) %>
        </div>
        <div class="col-md-2 col-xs-2 setMargin">
          <%= link_to t('.delete'), album_path(album), data: {confirm: t('.str_delete')}, method: :delete %>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-md-offset-5 col-xs-offset-5 col-xs-2 col-md-2">

      <%= link_to t('.new_album'), new_user_album_path %>
    </div>

  </div>
  <div class="row">
    <div class="col-md-offset-5 col-xs-offset-5 col-xs-2 col-md-2">

      <%= link_to t('.pictures_private'), dashboard_user_path(current_user) %>
    </div>

  </div>
  <div class="row">
    <div class="col-md-offset-5 col-xs-offset-5 col-xs-2 col-md-2">

      <%= link_to t('.pictures_public'), pictures_path %>
    </div>

  </div>

</div>
<div class="row">
    <div>
      <%= paginate @albums %>
    </div>
  </div>

Exercise/Exercise_New/app/views/albums/new.html.erb
<h1><%= t('.title_create_album') %></h1>

<%= render 'form', album: @album, url_link: user_albums_path %>

Exercise/Exercise_New/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExerciseNew</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <%# This is just an example, you can put `i18n.js` and `translations.js` anywhere you like %>
<%# Unlike the Asset Pipeline example, you need to require both **in order** %>

</head>

<body>
  <%= yield %>
</body>
</html>

Exercise/Exercise_New/app/views/notifications/another.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1><%= t('.title_welcome') %></h1>
  </body>
</html>

Exercise/Exercise_New/app/views/pictures/_form.html.erb
<div>

  <div class="row">
    <div>
      <%= form_for picture, url: url_link do |form| %>
      <%= form.file_field :image %>
      <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
      </p>

      <p>
        <%= form.label :description %><br>
        <%= form.text_area :desc %>
      </p>
      <p>
        <%= form.label :public %><br>
        <%= form.check_box :is_public %><br>
      </p>
      <p>
        <%= form.submit %>
      </p>

      <% end %>
    </div>
  </div>
</div>

Exercise/Exercise_New/app/views/pictures/edit.html.erb
<h1><%= t('.title_edit_picture')%></h1>
<%= render 'form', picture: @picture, url_link: picture_path %>

Exercise/Exercise_New/app/views/pictures/index.html.erb
  <div class="row bgForm">
    <% @pictures.each do |picture| %>
    <div class="col-md-3 col-xs-3 bgDivTest">

      <%= image_tag picture.image.url %>
      <div class="row">
        <div class="sizeText">
          <%= picture.title %>
        </div>
      </div>
      <div class="row">
        <div class="sizeText">
          <%= picture.desc %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-2 col-xs-2 col-md-offset-3 col-xs-offset-3 setMargin">
          <%= link_to t('.albums.index.edit'), edit_picture_path(picture) %>
        </div>
        <div class="col-md-2 col-xs-2 setMargin">
          <%= link_to t('.albums.index.delete'), picture_path(picture), data: {confirm: t('.str_delete')}, method: :delete %>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-md-offset-5 col-xs-offset-5 col-xs-2 col-md-2">
      <% if @album %>
      <%= link_to t('.new_picture'), new_album_picture_path %>
      <% end %>
    </div>

  </div>
  <div class="row">
    <div>
      <%= paginate @pictures %>
    </div>
  </div>

Exercise/Exercise_New/app/views/pictures/new.html.erb
<h1><%= t('.title_create_picture') %></h1>
<%= render 'form', picture: @picture, url_link: album_pictures_path %>

Exercise/Exercise_New/app/views/users/dashboard.html.erb
<div>
  <div class="row bgForm">
    <% @pictures.each do |picture| %>
      <div class="col-md-3 col-xs-3 bgDivTest">

        <img>
        <div class="row">
          <div class="sizeText">
            <%= picture.title %>
          </div>
        </div>
        <div class="row">
          <div class="sizeText">
            <%= picture.desc %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-2 col-xs-2 col-md-offset-3 col-xs-offset-3 setMargin">
            <%= link_to t('.albums.index.edit'), edit_picture_path(picture) %>
          </div>
          <div class="col-md-2 col-xs-2 setMargin">
            <%= link_to t('.albums.index.delete'), picture_path(picture), data: {confirm: t('.str_delete')}, method: :delete %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

 <!--  <div class="row">
    <div class="col-md-offset-5 col-xs-offset-5 col-xs-2 col-md-2">
      <% if @album %>
        <%= link_to 'abc', new_album_picture_path %>
      <% end %>
    </div>

  </div> -->

</div>

Exercise/Exercise_New/app/views/users/edit.html.erb
<div class="row">
  <div>
    <%= form_for @user, url: user_path do |form| %>

    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>
    <p>
      <%= form.submit %>
    </p>

    <% end %>
  </div>
</div>

Exercise/Exercise_New/app/views/users/index.html.erb
<div class="row bgForm">
    <% @users.each do |user| %>
    <div class="col-md-3 col-xs-3 bgDivTest">

      <div class="row">
        <div class="sizeText">
          <%= user.name %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-2 col-xs-2 col-md-offset-3 col-xs-offset-3 setMargin">
          <!-- <%= link_to t('users.index.edit'), edit_user_path(user) %> -->
           <%= link_to t('.albums.index.edit'), edit_user_path(user) %>
        </div>
        <div class="col-md-2 col-xs-2 setMargin">
          <%= link_to t('.albums.index.show'), user_albums_path(user) %>
        </div>
        <div class="col-md-2 col-xs-2 setMargin">
          <%= link_to t('.albums.index.delete'), user_path(user), data: {confirm: t('.str_delete')}, method: :delete %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <div class="row">
    <div>
      <%= paginate @users %>
    </div>
  </div>

Exercise/Exercise_New/app/views/users/show.html.erb
<h1><%= t('.home.index.current_user')%></h1>
<div class="row">
  <div>
    <%= form_for @user do |form| %>

    <p>
      <%= form.label :name %><br>
      <%= @user.name %>
    </p>
    <div class="row">
        <div class="col-md-2 col-xs-2 col-md-offset-3 col-xs-offset-3 setMargin">
          <%= link_to t('.albums.index.edit'), edit_user_path(@user) %>
        </div>
        <div class="col-md-2 col-xs-2 setMargin">
          <%= link_to t('.albums.index.show'), user_albums_path(@user) %>
        </div>
        <div class="col-md-2 col-xs-2 setMargin">
          <%= link_to t('.albums.index.delete'), user_path(@user), data: {confirm: t('.str_delete')}, method: :delete %>
        </div>
      </div>

    <% end %>
  </div>
</div>